# Site settings
title: Words and Magic
email: dan.oneill@live.ie
description: "I focus on storytelling, be that in art, graphic design, music, video, movies, games or well... anything really. I love the stories behind everything."
baseurl: ""
image: "http://wordsandmagic.com/words-and-magic-black-3-small.png"
url: "http://wordsandmagic.com"
exclude: [package.json,gruntfile.js,node_modules]
safe: false
gems:
  [jekyll-auto-image,jekyll-responsive-image,amp-jekyll]

# Build settings
markdown: kramdown
permalink: pretty

ftp_host: 'wordsandmagic.com'
ftp_dir: '/public_html/wordsandmagic.com/'
ftp_passive: false

# optional
ftp_port: 21                  # default 21
ftp_username: ${ftp-user}     # default read from stdin
ftp_password: ${ftp-pass} # default read from stdin

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/response-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  # base_path: _site

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: images/resized/%{width}/%{basename}